FROM rust

RUN rustup install nightly-2020-11-17 && rustup override set nightly-2020-11-17 && rustup component add rust-src --toolchain nightly-2020-11-17 && rustup component add llvm-tools-preview --toolchain nightly-2020-11-17
RUN cargo install bootimage

ENTRYPOINT []